baseURL = 'https://www.frenchfamily.fr/'
title = 'French Family'
disableHugoGeneratorInject = true
enableRobotsTXT = true

[languages]
  [languages.fr]
    direction = ''
    disabled = false
    label = ''
    locale = ''
    title = ''
    weight = 0

[params]
  description = "Site familial & blog technique"
  author = "Seb"
  dateFormat = "02/01/2026"

[build]
  writeStats = true

[imaging]
  resampleFilter = "lanczos"
  quality = 80

[taxonomies]
  category = 'categories'
  tag = 'tags'

[[menus.main]]
  name = 'Accueil'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Famille & Passions'
  pageRef = '/family'
  weight = 20

[[menus.main]]
  name = 'Blog Technique'
  pageRef = '/tech'
  weight = 30